" __   _(_)_ __ ___  _ __ ___
" \ \ / / | '_ ` _ \| '__/ __|
"  \ V /| | | | | | | | | (__
"   \_/ |_|_| |_| |_|_|  \___|



""" Before using Vim, you must export the location of this vimrc to the
""" MYVIMRC env var in your shell.



"""Required settings
set nocompatible " Take that, vi!
filetype off



""" """ Begin Plug settings """ """

"""Download and install Plug first, if it's not installed, and run it
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"""Initialize Plug
" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
"call plug#begin('~/.vim/plugged')
call plug#begin('~/.vim/bundle')


"""___ MY PLUGINS HERE ___"""

"Purdy colors
Plug 'blockloop/vim-codeschool'
Plug 'vim-scripts/midnight.vim'
Plug 'vim-scripts/midnight2.vim'
Plug 'chriskempson/tomorrow-theme', {'rtp': 'vim/'}
Plug 'flazz/vim-colorschemes'
Plug 'altercation/vim-colors-solarized'

"Syntax
Plug 'vim-scripts/fountain.vim'
Plug 'shawncplus/phpcomplete.vim'
Plug 'StanAngeloff/php.vim'
Plug 'scrooloose/syntastic'
Plug 'jiangmiao/auto-pairs'
Plug 'vim-scripts/yaifa.vim'

"Python specifically
Plug 'tmhedberg/SimpylFold'
Plug 'vim-scripts/indentpython.vim'
Plug 'nvie/vim-flake8'
autocmd BufRead,BufNewFile *.py,*.pyw let python_highlight_all=1

"Go specific
Plug 'fatih/vim-go', {'do': ':GoUpdateBinaries' }

"Java specific
Plug 'mikelue/vim-maven-plugin'
Plug 'JalaiAmitahl/maven-compiler.vim'
Plug 'cilquirm/javacomplete'
autocmd Filetype java compiler mvn
autocmd Filetype pom compiler mvn
function SetJavaOpts()
    setfiletype java
    "match these characters with %
    setlocal matchpairs=(:),{:},[:],<:>

    "eclipse style add a * comments
    setlocal comments-=s1:/*,mb:*,ex:*/
    setlocal comments+=fb:*

    "completion options
    setlocal cscopequickfix=s-,c-,d-,i-,t-,e-
    setlocal completeopt=longest,menuone
    setlocal completefunc=javacomplete#Complete
    "export java classpath as completion locations for javacomplete
    for i in split($CLASSPATH,":")|call javacomplete#AddClassPath(i)|endfor
endfunction
autocmd BufNewFile,Bufread *.java call SetJavaOpts()

" General master linter
Plug 'w0rp/ale'

"Misc make my life easier
Plug 'djoshea/vim-autoread'

"Debugging
Plug 'vim-scripts/Conque-GDB'
Plug 'Shougo/vimproc.vim', { 'do': 'make' }
Plug 'idanarye/vim-vebugger'

"Cool shit
Plug 'sjl/gundo.vim'
Plug 'xolox/vim-misc'
Plug 'xolox/vim-session'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'kien/ctrlp.vim'
Plug 'vim-scripts/RltvNmbr.vim'
Plug 'ervandew/supertab'
Plug 'ConradIrwin/vim-bracketed-paste'
Plug 'romainl/vim-cool'
Plug 'tpope/vim-fugitive'
Plug 'matze/vim-move'
Plug 'tpope/vim-surround'
Plug 'skywind3000/asyncrun.vim'

""Latex
Plug 'lervag/vimtex'
"Plug 'ying17zi/vim-live-latex-preview'

""Unite and Zotero
Plug 'Shougo/neomru.vim'
"Plug 'Shougo/unite.vim'
"Plug 'Shougo/denite.nvim'
"Plug 'rafaqz/citation.vim'

""Sometimes works sometimes doesn't
Plug 'tpope/vim-sensible'
Plug 'Valloric/YouCompleteMe', { 'do': 'git submodule update --init --recursive; git submodule sync --recursive && git submodule update && python3 ./install.py --clang-completer --system-libclang --go-completer' }

""Currently not in use
"Plug 'Yggdroot/indentLine'

"""___ END MY PLUGINS ___"""


call plug#end()
filetype plugin indent on
"filetype plugin on
syntax enable

""" """ End Plug settings """ """



""" Latex
let g:tex_flavor = 'latex'

"""ConqueGDB stuff
" For recent Python3 versions, ConqueGDB requires manually editing
" ~/.vim/bundle/Conque-GDB/autoload/conque_gdb/conque_gdb.py
" to change line 39:
" class RegisteredBpDict(collections.MutableMapping):
" to
" class RegisteredBpDict(collections.abc.MutableMapping):
let g:ConqueTerm_CloseOnEnd=1       " close conque when program ends running
let g:ConqueTerm_StartMessages=0    " display warning message if conqueTerm is configed incorrect
let g:ConqueGdb_Leader = '\'

"""Extra YCM stuff
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_error_symbol = '>>'
let g:ycm_warning_symbol = '>*'

"""Load powerline
let g:powerline_pycmd = 'py3'
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

"""Allow to replace current buffer window with new file using BDE /path/to/file
function! ReplaceBuffer(bang, newfile)
  let curbuf = bufnr('%')
  exec "e " . a:newfile
  exec "bd" . a:bang . " " . curbuf
endfunction
command! -nargs=1 -complete=file -bang -bar BDE call ReplaceBuffer('<bang>', <f-args>)

"""Refresh vimrc on save
if has ('autocmd') " Remain compatible with earlier versions
 augroup vimrc     " Source vim configuration upon save
    autocmd! BufWritePost $MYVIMRC source % | echom "Reloaded " . $MYVIMRC | redraw
    autocmd! BufWritePost $MYGVIMRC if has('gui_running') | so % | echom "Reloaded " . $MYGVIMRC | endif | redraw
  augroup END
endif " has autocmd

"""Python linter ignore E501 line too long
let g:syntastic_python_checkers=['flake8']
let g:syntastic_python_checker_args='--ignore=E501'
let g:syntastic_python_flake8_post_args='--ignore=E501'
let g:syntastic_python_flake8_args='--ignore=E501'
let g:ale_python_flake8_args='--ignore=E501'
let g:pymode_lint_ignore = "E501"

"""More Python and C++ highlighting
let python_highlight_all=1
let python_highlight_builtins=1
syn match pythonSelf   /\v(self|cls)/ contained
syn match pythonSelf   /\v(self|cls)/
syn match pythonDunder '__\w\+__'
syn match pythonMember /\vself\.\w+(\w|\()@!/hs=s+5 contains=pythonSelf
syn match pythonMember /\vcls\.\w+(\w|\()@!/hs=s+4 contains=pythonSelf
hi link pythonSelf    Identifier
hi link pythonDunder  Define
hi link pythonMember Type
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1

"""Zotero
let g:citation_vim_mode="zotero"
" My zotero library is a mounted partition
let g:citation_vim_zotero_path="~/mnt/Zotero"
let g:citation_vim_zotero_version=5
let g:citation_vim_cache_path='/tmp/vim_citation_cache'
let g:citation_vim_outer_prefix="["
let g:citation_vim_inner_prefix="@"
let g:citation_vim_suffix="]"
let g:citation_vim_et_al_limit=2
let g:citation_vim_reverse_order=1

"""Don't go back a char when leaving insert mode
au InsertLeave * call cursor([getpos('.')[1], getpos('.')[2]+1])

""" Don't save or load sessions unless I tell you to
let g:session_autosave = 'no'
let g:session_autoload = 'no'
let g:session_directory = '~/.vim/.vim-sessions'

"""But do autosave every few minutes
au BufRead,BufNewFile * let b:autosave_start_time=localtime()
au CursorHold * call UpdateFile()
" Try/catch used in function because it fails on empty new unnamed files, which I don't care about
function! UpdateFile()
  try
    if ((localtime() - b:autosave_start_time) >= 200)
      update
      let b:autosave_start_time=localtime()
    endif
  catch
    echo ""
  endtry
endfunction
au BufWritePre * let b:autosave_start_time=localtime()

"""This no last character thing is getting old fast
set virtualedit=onemore

"""Get cutting and pasting working by attempting to disable xorg sel buf
"""and setting default yank and paste to + buffer
set clipboard+=unnamedplus
au BufWrite * let @*=@+
au BufWrite + let @*=@+
let @*=@+
nnoremap <expr> y (v:register ==# '"' ? '"+' : '') . 'y'
nnoremap <expr> yy (v:register ==# '"' ? '"+' : '') . 'yy'
nnoremap <expr> Y (v:register ==# '"' ? '"+' : '') . 'Y'
xnoremap <expr> y (v:register ==# '"' ? '"+' : '') . 'y'
xnoremap <expr> Y (v:register ==# '"' ? '"+' : '') . 'Y'
nnoremap <expr> p (v:register ==# '"' ? '"+' : '') . 'p'
nnoremap <expr> P (v:register ==# '"' ? '"+' : '') . 'P'
xnoremap <expr> p (v:register ==# '"' ? '"+' : '') . 'p'
xnoremap <expr> P (v:register ==# '"' ? '"+' : '') . 'P'

"""Use sane puts
nmap p P
xmap p P
map p P

"""Delete should use its own buffer, not the main
nnoremap <expr> d (v:register ==# '"' ? '"d' : '') . 'd'
xnoremap <expr> d (v:register ==# '"' ? '"d' : '') . 'd'

"""utf-8 encoding is BEST ENCODING!!!
set encoding=utf-8

"""There are no carraige returns!
set fileformat=unix

"Either of these will cause carraige return (\r) line endings to display as ^M
"e ++ff=unix   "Set this while in the file as a :colon command
"set binary    "Set this here in the vimrc
"""Set one of these and enable the eol white space below to see full \r\n line endings

"""Turn on mouse, even though we shouldn't use it.
set mouse=a
set ttymouse=xterm2

"""Timeout for key presses
set ttimeout
set ttimeoutlen=100

"""Keep buffers
set hidden

"""Attempt to get indents correct
set autoindent
set complete-=i
set smarttab
let g:indentLine_enabled = 1
let g:indentLine_char = '┆'
let g:indentLine_leadingSpaceChar = '·'
let g:indentLine_leadingSpaceEnabled = 1

"""Show some whitespace
set listchars=tab:»·,trail:·,nbsp:·,extends:»,precedes:«
"set listchars+=space:·,eol:¬
"set listchars+=space:·
set list

"""Tabs are 4 spaces. Seriously. Make them 4 spaces. For real.
set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
"set nosmarttab

"""Misc other vim-sensible things
if v:version > 703 || v:version == 703 && has("patch541")
    set formatoptions+=j " Delete comment character when joining commented lines
endif
if has('path_extra')
    setglobal tags-=./tags tags-=./tags; tags^=./tags;
endif
if &shell =~# 'fish$' && (v:version < 704 || v:version == 704 && !has('patch276'))
    set shell=/bin/bash
endif
if !empty(&viminfo)
    set viminfo^=!
endif
set sessionoptions-=options
" Allow color schemes to do bright colors without forcing bold.
if &t_Co == 8 && $TERM !~# '^linux\|^Eterm'
    set t_Co=16
endif
" Load matchit.vim, but only if the user hasn't installed a newer version.
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
    runtime! macros/matchit.vim
endif

"""Show line numbers, both absolute and relative
set relativenumber
"call RltvNmbr#RltvNmbrCtrl(1)
"""Plugin takes up way too much processing power, so just using built-in
set number

"""Now make insert mode show absolute numbering only
autocmd InsertEnter * set relativenumber!
autocmd InsertLeave * set relativenumber

"""Caps lock mapped to Esc while in Vim
"autocmd VimEnter * silent !xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
"autocmd VimLeave * silent !xmodmap -e 'clear Lock' -e 'keycode 0x42 = Caps_Lock'
"""Nevermind, I just set that globally on my system all the time.

"""Nevermind, that 0.5 second pause every time I run it is going to be annoying,
"""so just map Esc to qq. After all, how often do you type qq?
"imap qq <Esc>
"map qq <Esc>
"""Turns out, never! This qq command is actually working out brillitantly!
"""Actually, with caps lock set, this isn't really necessary.

"""On second thought, you know what, I am keeping it.
imap qq <Esc>
map qq <Esc>


"""While we're at it, force ourselves to practice proper vim movement
"map <up> <nop>
"map <down> <nop>
"map <left> <nop>
"map <right> <nop>
"""Practice, practice, practice!!!
"imap <up> <nop>
"imap <down> <nop>
"imap <left> <nop>
"imap <right> <nop>


"""Leave insert mode after 5 seconds of not editing
function SetInsertOffTimer()
    autocmd InsertEnter * let updaterestore=&updatetime | set updatetime=5000
    autocmd InsertLeave * let &updatetime=updaterestore
    autocmd CursorHoldI * silent! stopinsert
endfunction
autocmd BufNew,BufNewFile,BufAdd,BufCreate,VimEnter * call SetInsertOffTimer()

"""And while we're forcing ourselves to develop good habits, we
"""might as well torture ourselves.
"noremap h <NOP>
"noremap j <NOP>
"noremap k <NOP>
"noremap l <NOP>
"""Nevermind that's too hard, I can't move, at all. Commenting those out
"""took like eight minutes.


"""{{{Fold}}}
set foldlevelstart=99
set foldmethod=indent
nmap <space> za

"""Don't create wierd new backup files I never asked for
set nobackup

"""Write backup is cool tho
set writebackup

"""Yes for the love of all that is holy please do keep a swap file in case of a crash
set swapfile

"""Show bottom info bar
set ruler

"""Remember everything
set history=999
set tabpagemax=50

"""Keep me front and center
set scrolloff=999

"""Finish my sentences for me
set showcmd
set wildmode=longest,list,full
set wildmenu

"""Scroll correctly
if !&scrolloff
    set scrolloff=1
endif
if !&sidescrolloff
    set sidescrolloff=5
endif
set display+=lastline

"""Show status
set laststatus=2

"""Remap vim-move movements to ctrl because terminal app captures alt key
let g:move_key_modifier = 'C'
"Ctrl+j and Ctrl+k move lines/selections up/down
"And {num}ctrl+j/k moves them up/down that number of lines

"""Always refresh
set autowrite
set autoread
autocmd FocusGained,BufEnter * :silent! !

"""If not in terminal, use a good font
if has('gui_running')
    if has('gui_win32')
        set guifont=DejaVu_Sans_Mono:h10:cANSI
    else
        set guifont=DejaVu\ Sans\ Mono\ 10
    endif
endif

"""Find matched braces
set showmatch

"""Don't use unnecessary resources
set lazyredraw

"""Set leader key to comma
let mapleader = ","

"""Improve searching
set gdefault
set ignorecase
"set smartcase
set hlsearch
nmap <silent> <leader>/ :noh<cr>
set incsearch
set showmatch
" Use <C-L> to clear the highlighting of :set hlsearch.
if maparg('<C-L>', 'n') ==# ''
    nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif

"""Some basic HTML fixes
set matchpairs+=<:>
let g:html_indent_tags = 'li\|p'

"""Some easy standard keys I want to use
set backspace=indent,eol,start
nmap <CR> $a<CR><Esc>
nmap <Del> i<Del>
nmap <BS> i<BS>
nmap <C-BS> dbi<Del><Esc>
imap <C-BS> <Esc>edbi<Del>
nmap <C-S-j> <PageDown>
imap <C-S-j> <PageDown>
nmap <C-S-k> <PageUp>
imap <C-S-k> <PageUp>
nmap <C-f> /
imap <C-f> <Esc>/
nmap <C-a> <nop>
imap <C-a> <nop>
vmap <C-a> <nop>
map <C-a> <nop>

"""Just making sure enter key map above doesn't mess things up
autocmd CmdwinEnter * nmap <CR> <CR>
autocmd BufReadPost quickfix nmap <CR> <CR>

"""Nerd Tree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
map <C-Bslash> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1

"""Do not wrap, darn it!
set linebreak
set textwidth=0
set wrapmargin=0
set formatoptions-=t

"""Ok, yes, wrap here
set wrap

"""Define function to not wrap because it keeps friggin wrapping, so we have to
"""manually disable it frequently.
function DisableAutoLineBreak()
    set wrap
    set linebreak
    set textwidth=0
    set wrapmargin=0
    set formatoptions-=t
endfunction
autocmd BufNew,BufNewFile,BufAdd,BufCreate,VimEnter * call DisableAutoLineBreak()

"""Sssssave and QQQQQQuit 
nmap sss :w<CR>
nmap qqq :wq<CR>
imap sss <Esc>:w<CR>i
imap qqq <Esc>:wq<CR>

"""Ctrl save and ctrl quit
"nmap <C-s> :w<CR>
"nmap <C-q> :w<CR>
"imap <C-s> <Esc>:w<CR>i
"imap <C-q> <Esc>:wq<CR>
"""Nevermind, terminal app doesn't let me hook those


" ALE Setting
let g:ale_open_list = 'on_save'             " show quickfix or locallist window
let g:ale_list_window_size = 5
let g:ale_set_loclist = 0                   " not use locallist show repeat reuslt
let g:ale_set_quickfix = 1                  " for different lint.
let g:ale_lint_delay = 500                  " lint after 500 ms.
let g:ale_lint_on_text_changed = 'normal'   " 'always' kind of annoying
let g:ale_lint_on_insert_leave = 1
let g:airline#extentions#ale#enabled = 0
let g:ale_linters = {
            \ 'python': ['pycodestyle'],
            \ 'cpp' : ['gcc','clang']
            \       }
" ALE C++ confiure
let g:ale_cpp_clang_options = '-std=c++11 -Wall -Wextra'
let g:ale_cpp_gcc_executable = 'g++'
let g:ale_cpp_gcc_options = '-std=c++11 -Wall -Wextra'
let g:ale_cpp_cppcheck_options = ''

"""No, do not hide things from me
set conceallevel=0
setlocal conceallevel=0
let g:vim_json_syntax_conceal = 0
set cole=0
au FileType * setl cole=0

"""Turn on purdy colors
set background=dark
colorscheme mydefault

"""Clean code should rarely exceed 80 chars per line
"""But don't wrap for me, just alert me to where it is
"let &colorcolumn=join(range(80,2000),",")
let &colorcolumn=80
highlight ColorColumn ctermbg=237
"highlight OverLength ctermfg=red
"match OverLength /\%>79v.\+/

"""Highlight current line
set cursorline
highlight CursorLine cterm=none ctermbg=237

"""Use highlight to tell me when I'm in insert mode
autocmd InsertEnter * highlight CursorLine cterm=none ctermbg=59
autocmd InsertLeave * highlight CursorLine cterm=none ctermbg=237

